### ISSUE TITLE
[Regression] Could not evaluate: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by jcpunk** [voxpupuli/puppet-augeasproviders_core#57]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.25.0
- Ruby: AIO bundled ruby
- Distribution: Almalinux 9
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)
```
include sysctl_conf
```
and
```yaml
sysctl_conf::values:
  fs.suid_dumpable:
    value: 0
    comment: do not core dump suid/sgid binaries
  fs.protected_hardlinks:
    value: 1
    comment: cannot link if do not have read/write access to it.
  fs.protected_symlinks:
    value: 1
    comment: cannot link if do not have read/write access to it.
  fs.protected_fifos:
    value: 2
    comment: cannot use fifo if do not have read and write access to it.
  vm.mmap_min_addr:
    value: 65536
    comment: non-root cannot user low mem
  vm.overcommit_memory:
    value: 0
    comment: should we overcommit memory
  vm.panic_on_oom:
    value: 0
```
And so on

## What are you seeing
Errors in catalog

## What behaviour did you expect instead
No errors

## Output log
```
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[fs.suid_dumpable]/Sysctl[fs.suid_dumpable]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[fs.protected_hardlinks]/Sysctl[fs.protected_hardlinks]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[fs.protected_symlinks]/Sysctl[fs.protected_symlinks]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[fs.protected_fifos]/Sysctl[fs.protected_fifos]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[vm.mmap_min_addr]/Sysctl[vm.mmap_min_addr]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[vm.overcommit_memory]/Sysctl[vm.overcommit_memory]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[vm.panic_on_oom]/Sysctl[vm.panic_on_oom]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.dmesg_restrict]/Sysctl[kernel.dmesg_restrict]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.domainname]/Sysctl[kernel.domainname]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.panic_on_oops]/Sysctl[kernel.panic_on_oops]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.task_delayacct]/Sysctl[kernel.task_delayacct]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.keys.root_maxbytes]/Sysctl[kernel.keys.root_maxbytes]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.keys.root_maxkeys]/Sysctl[kernel.keys.root_maxkeys]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.kptr_restrict]/Sysctl[kernel.kptr_restrict]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.perf_event_paranoid]/Sysctl[kernel.perf_event_paranoid]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.randomize_va_space]/Sysctl[kernel.randomize_va_space]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.sched_autogroup_enabled]/Sysctl[kernel.sched_autogroup_enabled]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.unprivileged_bpf_disabled]/Sysctl[kernel.unprivileged_bpf_disabled]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[kernel.yama.ptrace_scope]/Sysctl[kernel.yama.ptrace_scope]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[net.core.netdev_max_backlog]/Sysctl[net.core.netdev_max_backlog]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[net.ipv4.tcp_mtu_probing]/Sysctl[net.ipv4.tcp_mtu_probing]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[net.core.wmem_max]/Sysctl[net.core.wmem_max]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[net.core.rmem_max]/Sysctl[net.core.rmem_max]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[net.core.netdev_budget]/Sysctl[net.core.netdev_budget]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[vm.dirty_ratio]/Sysctl[vm.dirty_ratio]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[vm.dirty_background_ratio]/Sysctl[vm.dirty_background_ratio]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[vm.zone_reclaim_mode]/Sysctl[vm.zone_reclaim_mode]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[user.max_user_namespaces]/Sysctl[user.max_user_namespaces]: Could not evaluate: undefined method `[]' for nil:NilClass
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[user.max_net_namespaces]/Sysctl[user.max_net_namespaces]: Could not evaluate: undefined method `[]' for nil:NilClass
```

## Any additional information you'd like to impart
The previous vox version (`3.2.1`) is in use in my production environment without issues.

Working:
```
mod 'puppet-augeasproviders_core', '3.2.1'
mod 'puppet-augeasproviders_grub', '5.0.0'
mod 'puppet-augeasproviders_shellvar', '6.0.0'
mod 'puppet-augeasproviders_sysctl', '3.1.0'
mod 'deric-sysctl_conf', '0.4.0'
```

Not working:
```
mod 'puppet-augeasproviders_core', '4.0.0'
mod 'puppet-augeasproviders_grub', '5.0.0'
mod 'puppet-augeasproviders_shellvar', '6.0.0'
mod 'puppet-augeasproviders_sysctl', '3.1.0'
mod 'deric-sysctl_conf', '0.4.0'
```

**Comment by ekohl** [comment]
The only commit with a diff in `lib` is 31abd4b6af444a7dc35a40ddfa01a8ca1e2b7020. Do you happen to have a traceback? Perhaps if you enable debug output you can see it.

**Comment by jcpunk** [comment]
This is what I see in traceback

```
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[user.max_user_namespaces]/Sysctl[user.max_user_namespaces]: Could not evaluate: undefined method `[]' for nil:NilClass
/opt/puppetlabs/puppet/cache/lib/puppet/provider/sysctl/augeas.rb:258:in `block (2 levels) in <top (required)>'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:668:in `augopen_internal'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:98:in `augopen'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:718:in `augopen'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:166:in `block in define_aug_method'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property.rb:468:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1112:in `block in retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1107:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1107:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1130:in `retrieve_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:307:in `from_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:20:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:267:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:288:in `eval_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `block (2 levels) in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:567:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:566:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:122:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:178:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:238:in `block (2 levels) in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:567:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:566:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:237:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:165:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:151:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:236:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:286:in `block (2 levels) in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:567:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:566:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:285:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:245:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:244:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:284:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:500:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:339:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:83:in `block (6 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:289:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:82:in `block (5 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:81:in `block (4 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:71:in `block (3 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:162:in `with_client'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:67:in `block (2 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:127:in `run_in_fork'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:66:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:172:in `controlled_run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:47:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:433:in `onetime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:393:in `block in run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:289:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:390:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:756:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:143:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
Debug: Sysctl_conf::Entry[user.max_user_namespaces]: Resource is being skipped, unscheduling all events
Error: /Stage[main]/Sysctl_conf/Sysctl_conf::Entry[user.max_net_namespaces]/Sysctl[user.max_net_namespaces]: Could not evaluate: undefined method `[]' for nil:NilClass
/opt/puppetlabs/puppet/cache/lib/puppet/provider/sysctl/augeas.rb:258:in `block (2 levels) in <top (required)>'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:668:in `augopen_internal'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:98:in `augopen'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:718:in `augopen'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/augeasprovider/default.rb:166:in `block in define_aug_method'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property.rb:468:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1112:in `block in retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1107:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1107:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1130:in `retrieve_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:307:in `from_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:20:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:267:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:288:in `eval_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `block (2 levels) in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:567:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:566:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:122:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:178:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:238:in `block (2 levels) in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:567:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:566:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:237:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:165:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:151:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:236:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:286:in `block (2 levels) in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:567:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:566:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:285:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:245:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:244:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:284:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:500:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:339:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:83:in `block (6 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:289:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:82:in `block (5 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:81:in `block (4 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:71:in `block (3 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:162:in `with_client'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:67:in `block (2 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:127:in `run_in_fork'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:66:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:172:in `controlled_run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:47:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:433:in `onetime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:393:in `block in run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:289:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:390:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:756:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:143:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
Debug: Sysctl_conf::Entry[user.max_net_namespaces]: Resource is being skipped, unscheduling all events
```

**Comment by ekohl** [comment]
So that's https://github.com/voxpupuli/puppet-augeasproviders_sysctl/blob/57fe92aaa336e52517a41420281863b4075614a0/lib/puppet/provider/sysctl/augeas.rb#L258

```ruby
comment = aug.get("$target/#comment[following-sibling::*[1][self::#{resource[:name]}]][. =~ regexp('#{resource[:name]}:.*')]")
```

Looks like `resource` is `nil`, because that's the only thing that does `[]`. I think I see my error.
